name: Solve KNSP With CP-SAT

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      problem:
        description: 'Name of the problem to solve'
        required: true
        default: 'gcp_app_10_node_9'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Setup the environment
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip' # caching pip dependencies

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi
          python -m pip install ./models_or-tools

      - name: Run the script
        run: python ./models_or-tools/problems/${{ github.event.inputs.problem }}.py
